## Custom configuration

#server:
#  address: 192.168.1.2
#  reportRoot: /path/to/report/root

cortex:
  cortexServerAddress: localhost:54321
  headsetIdsToCodes:
    EPOCPLUS-3B9ADF08: A1
    EPOCPLUS-HU74KZ12: A2
  useSsl: false
  # Provide Emotiv credentials via command line
  emotiv:
    username: test-username
    password: test-password
    clientId: test-client-id
    clientSecret: test-client-secret
    appId: test-app-id

grpc:
  port: 9991
  master:
    type: static
    address: localhost:9992
  #masterLookupIntervalMillis: 5000
  masterSyncIntervalMillis: 1000

## Standard Bootique configuration

jetty:
  context: /
  connectors:
    - type: http
      port: 9998

jdbc:
  octopus:
    url: jdbc:postgresql://localhost:5432/octopus?currentSchema=octopus
    maxActive: 2
    username: postgres
    password: postgres

log:
  level: warn
  loggers:
    net.manaty:
      level: trace
  appenders:
    - type: console
      logFormat: '[%d{dd/MMM/yyyy:HH:mm:ss}] %t %-5p %c{1}: %m%n'